version: '3.7'
services:
	postgres:
		container_name: postgres
		build: ./postgres
		environment:
			POSTGRES_USER: admin
			POSTGRES_PASSWORD: password
			POSTGRES_URI: postgres://admin:password@localhost:5432/face-recognition
			POSTGRES_DB: face-recognition
			POSTGRES_HOST: postgres
		ports:
			- "5432:5432"

	face-recognition-api:
		container_name: backend
		build: ./
		volumes:
			- ./:/usr/src/face-recognition-api
		command: npm start
		working_dir: /usr/src/face-recognition-api
		ports:
			- "3000:3000"
		environment:
			POSTGRES_URI: postgres://admin:password@postgres:5432/face-recognition