version: '3.6'
services:
  # Main API Application
  face-recognition-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/face-recognition-api
    environment:
      DATABASE_URL: postgres://admin:password@postgres:5432/face-recognition
      REDIS_URL: redis://redis:6379
    links:
      - redis
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/face-recognition-api

  # PostgreSQL
  postgres:
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: face-recognition
        POSTGRES_HOST: postgres
    build: ./postgres
    ports:
        - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
